export default function handler(req, res) {
	res.status(200).json(productos);
}

// { name: 'pollo', weight: 'libra', brand: 'micasa', img: 'https://ttager.netlify.app/img/oaAhri4.jpg', },
const productos = [
	{
		brand: "Norteño",
		products: [
			{
				name: "Pollo entero",
				weight: 1,
				brand: "Norteño",
				sausage: false,
				img: "/image/products/1_norteño_pollo_entero_libra.jpg",
			},
			{
				name: "Pollo en mitades",
				weight: 1,
				brand: "Norteño",
				sausage: false,
				img: "/image/products/1_norteño_pollo_entero_libra.jpg",
			},
			{
				name: "Pollo en cuartos 🏠",
				weight: 1,
				brand: "Norteño",
				sausage: false,
				img: "/image/products/1_norteño_pollo_entero_libra.jpg",
			},
			{
				name: "Pierna con muslo",
				weight: 1,
				brand: "Norteño",
				sausage: false,
				img: "/image/products/1_norteño_pollo_entero_libra.jpg",
			},
			{
				name: "Menudos de pollo",
				weight: 1,
				brand: "Norteño",
				sausage: false,
				img: "/image/products/1_norteño_menudos_libra.jpg",
			},
			{
				name: "Patas de pollo",
				weight: 1,
				brand: "Norteño",
				sausage: false,
				img: "/image/products/1_norteño_patas_pollo.jpg",
			},
			{
				name: "Hot Dog de pollo",
				weight: 1,
				brand: "Norteño",
				sausage: true,
				img: "/image/products/2_norteño_hot_dog_de_pollo_1_libra.jpg",
			},
			{
				name: "Jamón de pollo",
				weight: 1 / 2,
				brand: "Norteño",
				sausage: true,
				img: "/image/products/2_norteño_jamon_de_pollo_1_2_libra.jpg",
			},
			{
				name: "Nuggets de pollo",
				weight: "c/u",
				brand: "Norteño",
				sausage: true,
				img: "/image/products/3_nortello_nuggets_pollo.jpg",
			},
			{
				name: "Alitas de pollo",
				weight: "c/u",
				brand: "Norteño",
				sausage: true,
				img: "/image/products/3_norteño_alitas_pollo.jpg",
			},
			{
				name: "Strips de pollo",
				weight: "c/u",
				brand: "Norteño",
				sausage: true,
				img: "/image/products/3_norteño_strips_pollo.jpg",
			},
		],
	},
	{
		brand: "San Antonio",
		products: [
			{
				name: "Patas de pollo",
				weight: 1,
				brand: "San Antonio",
				sausage: false,
				img: "/image/products/1_san_antonio_patas_de_pollo.jpg",
			},
			{
				name: "Pollo en cuartos 🏠",
				weight: 1,
				brand: "San Antonio",
				sausage: false,
				img: "/image/products/1_san_antonio_pollo_libra.jpg",
			},
		],
	},
	{
		brand: "Delicia",
		products: [
			{
				name: "C. Barbacoa",
				weight: 3,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_chorizo_barbacoa_3_libra.jpg",
			},
			{
				name: "Copetín",
				weight: 1,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_chorizo_copetin_1_libra.jpg",
			},
			{
				name: "extremeño",
				weight: 1,
				brand: "Delicia",
				img: "/image/products/2_delicia_chorizo_extremeño_delicia_1_libra.jpg",
			},
			{
				name: "Chorizo Parrillero Picante",
				weight: 1,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delcia_chorizo_barbacoa_1_libra.webp",
			},
			{
				name: "Chorizo Barbacoa",
				weight: 1,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_chorizo_parrillero_picante_1_libra.webp",
			},
			{
				name: "longaniza",
				weight: 1,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_chorizo_longaniza_1_libra.jpg",
			},
			{
				name: "longaniza",
				weight: 3,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_chorizo_longaniza_3_libra.jpg",
			},
			{
				name: "Jamón barvaria",
				weight: 1 / 2,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_jamon_bavaria_1_2_libra.jpg",
			},
			{
				name: "Jamón de pavo",
				weight: 1 / 2,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_jamon_de_pavo_1_2_libra.jpg",
			},
			{
				name: "Salchica Big dog",
				weight: 3,
				brand: "Delicia ",
				sausage: true,
				img: "/image/products/2_delicia_salchica_big_dog_1_libra.jpg",
			},
			{
				name: "Salchica con queso",
				weight: 3,
				brand: "Delicia",
				sausage: true,
				img: "/image/products/2_delicia_salchica_big_dog_1_libra.jpg",
			},
		],
	},
	{
		brand: "El porteño",
		products: [
			{
				name: "Chorizo cervecero",
				weight: 3,
				brand: "El porteño",
				sausage: true,
				img: "/image/products/2_el_porteño_chorizo_cervecero_3_libras.jpg",
			},
			{
				name: "Longaniza",
				weight: 3,
				brand: "El porteño",
				sausage: true,
				img: "/image/products/2_el_porteño_chorizo_longaniza_3_libras.jpg",
			},
		],
	},
	{
		brand: "Franks",
		products: [
			{
				name: "Hot Dog",
				weight: 3.75,
				brand: "Franks",
				sausage: true,
				img: "/image/products/2_franks_hot_dog_3.75_libras.jpg",
			},
			{
				name: "Mortadela en rollo",
				weight: "7 libras",
				brand: "Franks",
				sausage: true,
				img: "/image/products/2_franks_mortadela_7_libras.jpg",
			},
		],
	},
	{
		brand: "Pollo Rey",
		products: [
			{
				name: "Salchica de Pechuga",
				weight: 1,
				brand: "Pollo Rey",
				sausage: true,
				img: "/image/products/2_pollo_rey_salchicha_de_pechuga_1_libra.jpg",
			},
		],
	},
	{
		brand: "Toledo",
		products: [
			{
				name: "Choripollo",
				weight: 1,
				brand: "Toledo",
				sausage: true,
				img: "/image/products/2_toledo_choripollo_1_libras.jpg",
			},
			{
				name: "Mortadela",
				weight: " 7 libras",
				brand: "Toledo",
				sausage: true,
				img: "/image/products/2_toledo_mortadela_7_libras.jpg",
			},
			{
				name: "Hot dog",
				weight: 3.75,
				brand: "Toledo",
				sausage: true,
				img: "/image/products/2_toledo_salchica_hot_dog_3.75_libras.jpg",
			},
			{
				name: "Jumbo de  queso",
				weight: 1,
				brand: "Toledo",
				sausage: true,
				img: "/image/products/2_toledo_salchicha_jumbo_amc_con_queso.jpg",
			},
		],
	},
	{
		brand: "Carnes y mas...",
		products: [
			{
				name: "Pechuga sin hueso",
				weight: 1,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_pechuga_pollo_sin_hueso_1_libra.jpg",
			},
			{
				name: "Pechuga de pollo",
				weight: 1,
				brand: "",
				sausage: false,
				img: "/image/products/3_pollo_pechuga_libra.jpg",
			},
			{
				name: "Pierna de pollo con muslo",
				weight: 1,
				brand: "",
				sausage: false,
				img: "/image/products/3_pierna_con_muslo_de_pollo_libra.jpg",
			},
			{
				name: "Pollo en piezas fresco",
				weight: 1,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_pollo_cuartos_fresco_1 4.jpg",
			},
			{
				name: "Carcasa de Pollo",
				weight: 1,
				brand: "",

				sausage: false,
				img: "/image/products/1_n_carcasa_de_pollo_1_libra.jpg",
			},
			{
				name: `Chorizo criollo`,
				weight: 10,
				brand: "De Mi Casa",
				sausage: true,
				img: "/image/products/3_DeMiCasa_chorizo_criollo_pack_10_media_libra.jpg",
			},
			{
				name: "Chuleta de Cerdo",
				weight: 10,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_chuleta_de_cerdo_10_libras.jpg",
			},
			{
				name: "Costilla en cubos",
				weight: 10,
				brand: "",
				sausage: false,
				img: "/image/products/3_costilla_en_cubos_10_libras.jpg",
			},
			{
				name: "Chuleta de Cerdo ahumada",
				weight: 10,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_chuleta_de_cerdo_ahumada_libra.jpg",
			},
			{
				name: "Costilla ahumada",
				weight: 5,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_costilla_ahumada_1_libra.jpg",
			},
			{
				name: "Costilla en cubos",
				weight: 10,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_costilla_cubos_libra.png",
			},
			{
				name: "Molleja",
				weight: 1,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_molleja_libra.jpg",
			},
			{
				name: "Papas para freír",
				weight: 5.52,
				brand: "",
				sausage: true,
				img: "/image/products/3_papas_fritas_5.52_libras.jpg",
			},
			{
				name: "Frijoles Molidos",
				weight: 10,
				brand: "Gutti",
				sausage: true,
				img: "/image/products/3_frijoles_gutti_10_libras.jpg",
			},
			{
				name: "Patas de Cerdo",
				weight: 10,
				brand: "",
				sausage: false,
				img: "/image/products/1_n_patas_cerdo_libra.jpg",
			},
		],
	},
];
